language: bash
services: docker

env:
  - VERSION=9.6
  - VERSION=10
  - VERSION=11

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="geelweb/postgis:$VERSION"

script:
  - docker build --pull -t "$image" .
  - ~/official-images/test/run.sh -c ~/official-images/test/config.sh -c "../test/postgis-config.sh" "$image"
